/******************************************
 * @name 网易云音乐
 * @description 解锁会员歌曲、音质
******************************************

hostname = interface*.music.163.com
^https?:\/\/interface\d?\.music\.163\.com\/e?api\/vip\/cashier\/tspopup\/get url reject-200
^https?:\/\/interface\d?\.music\.163\.com\/e?api\/(mine\/collect\/header\/info|v\d\/user\/detail\/\d+|vipnewcenter\/app\/resource\/newaccountpage|music-vip-membership\/(client|front)\/vip\/info|batch|playlist\/privilege|search\/complex\/page|v\d\/(discovery\/recommend\/songs|playlist\/detail)) url script-response-body https://raw.githubusercontent.com/zhengdeyi18/jiaoben/main/wyy.js
^https?:\/\/interface\d?\.music\.163\.com\/e?api\/(song\/enhance\/player\/url\/v\d|vipauth\/app\/auth\/query) url script-analyze-echo-response https://raw.githubusercontent.com/zhengdeyi18/jiaoben/main/wyy.js
******************************************
(()=>{const e=new function(e){class t{constructor(e){this.env=e}send(e,t="GET",s){e="string"==typeof e?{url:e}:e,"POST"===t?this.post.call(this.env,e,s):this.get.call(this.env,e,s)}get(e,t){e.headers&&(delete e.headers["Content-Type"],delete e.headers["Content-Length"]),$httpClient.get(e,((e,s,o)=>{!e&&s&&(s.body=o,s.statusCode=s.status?s.status:s.statusCode,s.status=s.statusCode),t(e,s,o)}))}post(e,t){e.headers&&delete e.headers["Content-Length"],$httpClient.post(e,((e,s,o)=>{!e&&s&&(s.body=o,s.statusCode=s.status?s.status:s.statusCode,s.status=s.statusCode),t(e,s,o)}))}}return new class{constructor(e){this.name=e,this.http=new t(this)}getEnv(){return"Loon"}isLoon(){return!0}log(...e){console.log(e.join(" "))}done(e={}){$done(e)}}(e)}("𝐍𝐞𝐭𝐞𝐚𝐬𝐞𝐂𝐥𝐨𝐮𝐝𝐌𝐮𝐬𝐢𝐜"),t="undefined"==typeof $response,s=t?{status:200,headers:"undefined"==typeof $request?{}:$request.headers,body:""}:$response;!async function(){try{let o;if(t){const t=$request.method.toLowerCase(),s={url:$request.url,headers:$request.headers};"post"===t&&(s.body=$request.body);const{body:n}=await new Promise(((o,n)=>{e.http[t](s,((e,t,s)=>{e?n(e):o({resp:t,body:s})}))}));o=n}else if(o=s.body||s.bodyBytes,!o)return void e.done({});const n=$request.url.replace(/^(?:https?:\/\/)?(?:www\.)?[^\/]+(\/[^?#]*)?.*$/,"$1"),r=t?btoa(encodeURIComponent(JSON.stringify({url:$request.url,method:$request.method,data:$request.body}))):function(e){let t="";const s=new Uint8Array(e),o=s.byteLength;for(let e=0;e<o;e++)t+=String.fromCharCode(s[e]);return btoa(t)}(o),a={url:"https://free.yuhengy17.me/api/v2/",headers:{"x-id":"netease","Content-Type":"application/json;charset=UTF-8","x-tools-id":encodeURIComponent("Loon")},body:JSON.stringify({params:r,path:btoa(encodeURIComponent(n))})},d=await new Promise(((t,s)=>{e.http.post(a,((e,o,n)=>{e?s(e):t(n)}))})),u=JSON.parse(d),i=u.code,h=u.data,l=u.message;if(200===i){const o=function(e){const t=atob(e),s=t.length,o=new Uint8Array(s);for(let e=0;e<s;e++)o[e]=t.charCodeAt(e);return o}(h);t?e.done({}):(s.body=o,e.done(s))}else e.log("Request failed: "+l),e.done(s)}catch(t){e.log("Network request failed",t.message),e.done(s)}}()})();
