name: Update Password and Sync to WebDAV

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FLASHX }} # 使用你在仓库中设置的秘密

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate new password and update file
        run: node FlashXPass.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update password" --allow-empty
          git push origin HEAD:main # 确保推送到正确的分支

      - name: Sync to WebDAV
        env:
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          WEBDAV_USERNAME: ${{  secrets.WEBDAV_USERNAME }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          curl -T FlashX.conf $WEBDAV_URL --user $WEBDAV_USERNAME:$WEBDAV_PASSWORD
