const axios = require('axios');

function generateRandomDeviceId() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = (Math.random() * 16) | 0, v = c == 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  }).toUpperCase();
}

let random_device_id = generateRandomDeviceId();

let payload_login = {
  "deviceId": random_device_id,
  "deviceType": "1",
  "deviceInfo": "iPhone 13"
};

axios.post('https://api.mastur.xyz/client/user/firstDeviceLogin', payload_login, {
  headers: {
    'system-version': '16.3',
    'Accept': '/',
    'version': '1.1.25',
    'Authorization': '',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'zh-CN',
    'platform': '1',
    'Content-Type': 'application/json',
    'User-Agent': 'FlashX VPN',
    'Connection': 'keep-alive'
  }
}).then(resp_login => {
  let token = resp_login.data.token;

  axios.get('https://api.mastur.xyz/client/home/getConfigYaml?adblock=true&website=false', {
    headers: {
      'accept': '/',
      'platform': '/',
      'system-version': '15.6',
      'version': '1.1.24',
      'user-agent': 'BackgroundShortcutRunner/1355.1 CFNetwork/1404.0.5 Darwin/22.3.0',
      'accept-language': 'zh-CN',
      'authorization': token,
      'accept-encoding': 'gzip, deflate, br'
    }
  }).then(resp_config => {
    let passwordMatch = resp_config.data.match(/password: (\S+)/);
    if (passwordMatch && passwordMatch.length > 1) {
      let password = passwordMatch[1];
      console.log(password); // 输出密码，以便在GitHub Actions中捕获
    } else {
      console.error('No password found in the response data.');
      process.exit(1); // 如果没有找到密码，退出程序
    }
  });
}).catch(error => {
  console.error('An error occurred:', error);
  process.exit(1); // 如果发生错误，退出程序
});

