name: Update Password

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Generate new password and update file
        run: |
          PASSWORD=$(node FlashXPass.js)
          sed -i "s/password=[a-zA-Z0-9]*+/password=$PASSWORD/g" FlashX.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add FlashX.txt
          git commit -m "Update password" --allow-empty
          git push
